java \
-Dserver.port=8081 \
-Dspring.datasource.url=jdbc:mariadb://localhost:3306/carpmapsws \
-Dspring.datasource.driverClassName=org.mariadb.jdbc.Driver \
-Dspring.datasource.username=carpmapsws \
-Dspring.datasource.password=password \
-Dsecurity.service.secret=secret \
-Dsecurity.service.valid.apps=carp-bm \
-Dsecurity.service.valid.uids=uid \
-jar target/carp-maps-rest-api-0.0.1.jar
