@startuml

'!theme mono
'COMMENT - skinparam linetype ortho

interface cli as "CLI"
interface restserverrest as "REST"
interface ui as "UI"

component restserver as "rest server" {
    component rsjpapersistence as "jpa-persistence"
    component rsrest as "rest"
    component rsserver as "server"
    component rsservice as "service"
    component rsserviceinterface as "service-interface"

    rsjpapersistence --> rsserviceinterface

    rsserver --> rsserviceinterface

    rsservice --> rsserviceinterface
}

component shell {
    component shclient as "client"
    component shgui as "gui"
    component shrest as "rest"
    component shrestclient as "rest-client"
    component shserviceinterface as "service-interface"
    component shserver as "server"

    shclient --> shserviceinterface

    shgui -RIGHT-> shserviceinterface

    shrestclient --> shclient
    shrestclient --> shrest
    shrestclient --> shserver

    shserver --> shserviceinterface

    restserverrest )-- shclient
}

component swinggui as "swing gui" {
    component client
    component gui
    component rest
    component restclient as "rest-client"
    component serviceinterface as "service-interface"
    component server

    client --> serviceinterface

    gui -RIGHT-> serviceinterface

    restclient --> client
    restclient --> rest
    restclient --> server

    server --> serviceinterface

    restserverrest )-UP- client
}

cli -- shell
ui -- swinggui

restserver -UP- restserverrest

@enduml