@startuml

'!theme mono
'COMMENT - skinparam linetype ortho

interface cli as "CLI"
interface restserverrest as "REST"
interface ui as "UI"

component restserver as "rest server" {
    component rsbaselib as "base-lib"
    component rsjpapersistence as "jpa-persistence"
    component rsclient as "client"
    component rsrest as "rest"
    component rsserver as "server"
    component rsservice as "service"
    component rsserviceinterface as "service-interface"

    rsjpapersistence --> rsserviceinterface

    rsrest --> rsclient

    rsservice --> rsserviceinterface

    rsserviceinterface --> rsbaselib
}

component shell {
    component shbaselib as "base-lib"
    component shclient as "client"
    component shrest as "rest"
    component shrestclient as "rest-client"
    component shserviceinterface as "service-interface"
    component shserver as "server"

    shrest --> shclient

    shrestclient --> shbaselib
    shrestclient --> shclient
    shrestclient --> shrest

    restserverrest )-- shclient
}

component swinggui as "swing gui" {
    component baselib as "base-lib"
    component client
    component gui
    component rest
    component restclient as "rest-client"
    component serviceinterface as "service-interface"
    component server

    gui -DOWN-> baselib
    gui -RIGHT-> client

    rest --> client

    restclient --> baselib
    restclient --> client
    restclient --> rest

    serviceinterface --> baselib

    restserverrest )-UP- client
}

cli -- shell
ui -- swinggui

restserver -UP- restserverrest

@enduml