@startuml

'!theme mono
'COMMENT - skinparam linetype ortho

component baselib as "base-lib"
component client
component gui
component jpaservice as "jpa-service"
component rest
component restclient as "rest-client"
component restserver << application >> as "rest-server" #gold
component server
component service
component serviceinterface as "service-interface"
component shell << application >> #gold
component swing << application >> as "swing-gui" #gold

gui --> baselib
gui --> client

jpaservice --> serviceinterface

rest --> client

restclient --> baselib
restclient --> client
restclient --> rest

restserver ..> jpaservice
restserver --> rest
restserver --> server
restserver --> service

service --> serviceinterface

serviceinterface --> baselib

shell --> restclient

swing --> restclient
swing --> gui

@enduml