@startuml

'!theme mono
'COMMENT - skinparam linetype ortho

component client
component jpaservice as "jpa-service"
component rest
component restserver as "rest-server"
component service
component shell
component swing as "swing-gui"

client --> rest

jpaservice --> service

rest --> service

restserver --> rest
restserver --> jpaservice

shell --> client

swing --> client

@enduml